name: Release

on:
  push:
    tags:
      - 'v[0-9].[0-9].[0-9]'

jobs:
  call-build:
    uses: ./.github/workflows/ci.yml

  create-release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Download ISO artifact
        uses: actions/download-artifact@v3
        with:
          name: mhos-iso
          path: ./build/root/mhos-${{ github.ref_name }}.iso
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          draft: false
          tag_name: ${{ github.ref_name }}
          files: ./build/root/mhos-${{ github.ref_name }}.iso